apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-v2
  namespace: geolocation
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  fstype: ext4
  replication-type: none